Feature/organization
SprocketBot/sprocket-core pull request #16
Opened 2022-01-19 23:51 UTC by andreasmwenzel

Use validator pipe
Add UpdateOrganizationProfile resolver to graphql with an inputtype

can update organization profile with 
```
mutation{
  updateOrganizationProfile(
    id:3,
    profile:{
      websiteUrl:"mailto://this@ur.com",
      primaryColor:"#FFFF",
      logoUrl:"hippy@com.com"
    }
  ){
    name,
    description,
    primaryColor,
    secondaryColor,
    logoUrl,
    websiteUrl
    
  }
}
```

2022-01-20 01:42 UTC, andreasmwenzel commented
We can revert the change to the service. It should not have a type related to graphQL validation

2022-01-20 16:37 UTC, andreasmwenzel commented
It seems pretty standard practice to create these "Input types"

nestjs example: https://docs.nestjs.com/graphql/mutations#code-first
graphql post: https://graphql.org/learn/schema/#input-types

My issue with them is that they're not very DRY and we have to write a new type, pretty much anytime we're defining a new mutation if we want something more complex than "string" "Int", etc

But, if we could get something like the following working, we would be able to decorate our models with which are inputs, which are object fields, and which are both.  I think to do this, we would need to create the schema using this library and pass that onto the GraphQLModule's forRoot function. I do not yet know how it plays with zeus and the rest of the work you've done
https://owencalvin.github.io/graphql-composer-decorators/types/input-type.html#inputfield

I'm not sure how that will play out when we start thinking about permissions. Currently, you would just create another input type for a new mutation that has less fields, then protect your different mutations based on the permissions in the perm bearer.

2022-01-20 16:43 UTC, andreasmwenzel commented
> We can revert the change to the service. It should not have a type related to graphQL validation

This is done

2022-01-21 03:39 UTC, zachstence requested changes

2022-01-21 03:39 UTC, zachstence commented on src/database/organization/organization_profile/organization_profile.input.ts
> +    websiteUrl: string;
Since these properties are decorated with `{nullable: true}` and `@IsOptional()`, we should have the properties be optional (e.g. `websiteUrl?: string;`)

2022-01-21 03:39 UTC, zachstence commented on src/organization/organization/organization.resolver.ts
> +        @Args("id", {type: () => Int}) id: number,
I think we should use GraphQL's `Id` here instead of `Int`. @0c370t thoughts?

2022-01-21 03:41 UTC, zachstence commented
I think having the `InputTypes` be separate definitions is fine. Here it seems trivial and verbose, but for some more complex endpoints the inputs won't be exactly the same as the models. They may have additional/fewer fields, or different types than what our data model has.

2022-01-25 19:43 UTC, 0c370t commented
+1 on input types; those are a fundamental part of graphql and must be used.

2022-01-25 19:45 UTC, 0c370t commented on src/organization/organization/inputs/organization_profile.input.ts
> +export class OrganizationProfileInput implements Partial<OrganizationProfile> {
Why do we need the implements here?

2022-01-25 19:45 UTC, 0c370t commented on src/organization/organization/organization.resolver.ts
> +    async getOrganizationById(@Args("id", {type: () => ID}) id: number): Promise<Organization> {
is `ID` numeric?

2022-01-27 04:35 UTC, merged