Finalize Matchmaking Service Alph
SprocketBot/sprocket-core pull request #20
Opened 2022-02-06 01:17 UTC by 0c370t

2022-02-07 00:23 UTC, zachstence requested changes

2022-02-07 00:23 UTC, zachstence commented on src/scrim/scrim.module.ts
> +    providers: [ScrimModuleResolver,
Maybe rename to `ScrimsResolver` since it manages `Scrim`s?

2022-02-08 03:45 UTC, 0c370t commented on src/scrim/scrim.module.ts
> +    providers: [ScrimModuleResolver,
That seems easy to confuse with `ScrimResolver` and `ScrimsResolver`

2022-02-10 01:04 UTC, zachstence approved these changes

2022-02-10 01:15 UTC, merged